name: Build Apk
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Sign with debug key
      run: |
        sed -i "19i signingConfig signingConfigs.debug" ./app/build.gradle
        curl -s https://raw.githubusercontent.com/artem-zinnatullin/RxJavaProGuardRules/master/rxjava-proguard-rules/proguard-rules.txt | tee -a ./app/proguard-rules.pro
        cat ./app/proguard-rules.pro

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # Adopt is deprecated, use temurin now
        java-version: '11'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Get App Version Name
      id: version
      run: echo "app_version=$(grep versionName app/build.gradle | sed -n 's/.*versionName \"\([0-9.]*\)\".*/\1/p')" >> $GITHUB_ENV

    - name: Rename APK
      run: mv app/build/outputs/apk/debug/app-debug.apk game-unlocker-v${{ env.app_version }}.apk

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: Game Unlocker
        path: game-unlocker-v${{ env.app_version }}.apk

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create 8.0.0 game-unlocker-v${{ env.app_version }}.apk --title "${{ env.app_version }}" --notes "Automated release created by GitHub Actions"

